[google_service_account]
type = "service_account"
project_id = "appfinanliz"
private_key_id = "3e2ba6c5166320fb05fe9ce401bcba078e3da17b"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDGAGv7mnAk3Cr/
TXy923olVhlyOFNBkflMVU/+vehgynYEIri3940TGIXy6cuG+ZhgSGKNpLHbgCs3
Do16HvGR/VZR+TKJAL4wX0trQA2IMrPqFf4TJN6O13O6Tj9cU9Pl8LF0CQd5N7Ef
00/2A38l/CheKnHXIloyUFsmc847bB9Pa1yiRmmtA8dd2nh7h89SKcRH6Uk6QP4q
heBDoth2HCIR9fVwklmqFhRRIUSQ0sZhjGEXMT89QJnLNkCdo+V0n2if6NuPjCZm
8132c1T3/EhHdxDkvNp4ED1aq5BsHLg2JIvRw4ZisptlZp8bsb9hVxXm8nsOuJhH
Q6fU0EsJAgMBAAECggEAAjIDs7E305mZiqWhDH9Bu80lCi8FZOZGfmbTjkmsQsbg
tDVVv3wJu7+4NbDxoWnXwbkjvWbPuwhd6+Xn9ZK6XBBHRzCAZsqT96s8bDBaxg5F
... (continúa TODO hasta el final) ...
-----END PRIVATE KEY-----"""
client_email = "finanzas-app-service@appfinanliz.iam.gserviceaccount.com"
client_id = "100699168801589763879"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/finanzas-app-service%40appfinanliz.iam.gserviceaccount.com"